summarizer:
  module: 'summarizer.three_point'
  class: 'Bk'
  args: 
    grid: 256
    BoxSize: 1000
    k1: [0.01, 0.02, 0.03, 0.05, 0.08, 0.13, 0.22, 0.36, 0.6 , 1.  ]
    k2: [0.01, 0.02, 0.03, 0.05, 0.08, 0.13, 0.22, 0.36, 0.6 , 1.  ]
    theta: [0.3  , 0.6, 1.05 , 1.4, 1.8 , 2.0]
    n_threads: 16

catalogues:
  simulation_suite: 'quijote'
  nodes: range(2000)
  args:
    redshift: 0.5
    path_to_lhcs: '/global/cscratch1/sd/spandey/quijote/Halos/latin_hypercube'
    # n_density_halos: 1.1e-4
    n_halos: 1000

output_path: '/global/cscratch1/sd/spandey/quijote/Bk/'

