summarizer:
  module: 'summarizer.two_point'
  class: 'TPCF'
  args: 
    r_bins: np.linspace(0.,150.,50)
    mu_bins: np.linspace(-1.,1.,120)
    ells: [0,2,4]
    n_threads: 1

catalogues:
  simulation_suite: 'quijote'
  nodes: [0,2,]
  args:
    redshift: 0.5
    path_to_lhcs: '/n/holystore01/LABS/itc_lab/Users/ccuestalazaro/quijote/latin_hypercube'
    n_halos: 100000

output_path: 'test_data/'

